# github_token: "AUQKCEL5H6TFEO6QQFTICVLJIPVEA"
# github_token: AUQKCEI33FWTVOQQOPODVUDJIP2ZY
github_token: AUQKCENFZ6J5JWGFNHS43OLJNTVLG

postgres_password: 
grafana_admin_password:

user_mail: dansoug@gmail.com